---
output: html_document
---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

# AuralML
Description:
AuralML (working/temporay project name) is a suite of hardware and software solutions for the healthcare and medical industry.

## Status

Date | Action                                 | Status
-----|----------------------------------------|-------
31Mar17| Waiting for the evaluation kit, UPS tracking number is: [1Z4R29Y30348087114](https://wwwapps.ups.com/WebTracking/track) | 
27Mar17| Ordered the dev kit: STEVAL-STLKT01V1 from STMicroelectronics. After reading through the docs I am more confident |
23Mar17| Local 3D printing guy made two more stethoscope heads.| done
. | Tubbing, and stamp to make the mylar-membrane ordered from Amazon.com;| done
20MAR17| Got all the parts 3D printed to build one low-cost stethoscope| done
. | Prior to this date, I found out that the other Bluetooth Low power modules with microphone cannot send audio over the air, so after discussing it with Kristin, it doesn't make sense to continue that development.| done


## Head Design
Using the head from GliaX Free Medical [Github repository](https://github.com/GliaX)
- We have prited several heads 
- We have one complete stethoscope

## Bluetooth Devices
### STMicroelectronics
This product sounds to be the most promising one. I am currently waiting for delivery of this 
device.

- [STEVAL-STLKT01V1](http://www.st.com/content/st_com/en/products/evaluation-tools/solution-evaluation-tools/sensor-solution-eval-boards/steval-stlkt01v1.html)


### DIGI PAGE
- https://www.digikey.com/en/articles/techzone/2016/nov/how-to-deploy-bluetooth-based-iot-design-under-40

### Others
- http://www.sensiedge.com
- http://www.ti.com/tool/cc2650stk
- https://www.ralfebert.de/tutorials/


### Interface potential
- http://community.silabs.com/t5/Bluetooth-Wi-Fi/Thunderboard-How-stream-data-directly-to-cloud/m-p/182060#M14745

### iOS Bluetooth
- https://developer.apple.com/bluetooth/

### Firebase (cloud services)
- https://www.raywenderlich.com/139322/firebase-tutorial-getting-started-2
- [Configuring](https://firebase.google.com/docs/ios/setup)


### Bluetooth Modules
- [EasyVR-Voice-Recognition](https://developer.mbed.org/components/EasyVR-Voice-Recognition/)
- [Interactive Design (Berkeley)](https://bcourses.berkeley.edu/courses/1376830/pages/class-16-bluetooth)
- [Ti](http://www.ti.com/tool/TIDC-CC2650STK-SENSORTAG)

# Makezine
- http://makezine.com/2013/04/18/teardown-of-the-ti-sensortag/

## Developer Notes

#### StackOverflow Links
- [](http://stackoverflow.com/questions/18378049/how-to-record-the-voice-from-bluetooth-device-mic-and-play-in-device-speaker)
- [Xcode or Nodejs](http://stackoverflow.com/questions/33061371/macbook-pro-2015-connecting-to-a-ti-sensortag-cc2541)

